In [42]:
import pandas as pd
import numpy as np
import sklearn

data = pd.read_csv("training_ccpp_x_y_train.csv")
X_train = data.iloc[:,0:4]
y_train = data.iloc[:,4]
X_test = pd.read_csv("test_ccpp_x_test.csv",header=None)
X_test.columns = X_train.columns
X_test["Aux"] = np.ones((X_test.shape[0]))
X_train["Aux"] = np.ones((X_train.shape[0]))

In [43]:
X_train.values

array([[8.58000e+00, 3.83800e+01, 1.02103e+03, 8.43700e+01, 1.00000e+00],
       [2.17900e+01, 5.82000e+01, 1.01721e+03, 6.67400e+01, 1.00000e+00],
       [1.66400e+01, 4.89200e+01, 1.01155e+03, 7.87600e+01, 1.00000e+00],
       ...,
       [2.98000e+01, 6.93400e+01, 1.00936e+03, 6.47400e+01, 1.00000e+00],
       [1.63700e+01, 5.43000e+01, 1.01794e+03, 6.36300e+01, 1.00000e+00],
       [3.01100e+01, 6.20400e+01, 1.01069e+03, 4.79600e+01, 1.00000e+00]])

In [44]:
y_train.values

array([482.26, 446.94, 452.56, ..., 437.65, 459.97, 444.42])

In [45]:
X_test.shape

(2392, 5)

In [53]:
def step_gradient(X_train,y_train,m,learning_rate):
    M = len(X_train)
    m_slope = np.zeros((X_train.shape[1]))
    for i in range(M):
        x = X_train[i]
        y = y_train[i]
        for j in range(X_train.shape[1]):
            m_slope[j] += (-2/M)* (y - sum(m*x))*x[j]
            m[j]=m[j]-learning_rate*m_slope[j]
    m = m - learning_rate*m_slope
    return m

In [54]:
def cost_function(X_train,y_train,m):
    cost = 0
    M = len(X_train)
    for i in range(len(data)):
        cost += (y_train[i]-(m*X_train[i]).sum())**2
    return cost/M

In [55]:
#gradient descent
def gradient_descent(X_train,y_train,learning_rate,iteration):
    m = np.zeros((X_train.shape[1]))
#     m[data.shape[1]-1] = 1
    for i in range(iteration):
        m = step_gradient(X_train,y_train,m,learning_rate)
        print("Cost: ",cost_function(X_train,y_train,m))
    return m
m = gradient_descent(X_train.values,y_train.values,0.000000501,100)
m


Cost:  2852.152495311375
Cost:  56.104293037012354
Cost:  50.13190084468075
Cost:  42.211370529642565
Cost:  39.51643031447052
Cost:  38.04402761208195
Cost:  37.035851552524534
Cost:  36.22538378186825
Cost:  35.52019891049817
Cost:  34.88400247751753
Cost:  34.300387959808546
Cost:  33.76063010519485
Cost:  33.25931486693871
Cost:  32.792627013834476
Cost:  32.35760984150208
Cost:  31.951814008191917
Cost:  31.573117700758925
Cost:  31.219628818658425
Cost:  30.889628990598574
Cost:  30.58153988543211
Cost:  30.293901772948065
Cost:  30.025358981062503
Cost:  29.77464933184765
Cost:  29.540595943396262
Cost:  29.322100495994956
Cost:  29.118137453412565
Cost:  28.927748947514885
Cost:  28.75004015553422
Cost:  28.58417506731625
Cost:  28.429372577720528
Cost:  28.28490286140879
Cost:  28.15008399933771
Cost:  28.024278834045543
Cost:  27.906892034884436
Cost:  27.797367357670716
Cost:  27.695185084708534
Cost:  27.59985963292741
Cost:  27.510937318784507
Cost:  27.42799426942187
Cost

array([-1.6490132 , -0.28056149,  0.50315791, -0.09644199,  0.00286691])

In [57]:
def predict(m,X_test):
    y_pred = np.zeros(len(X_test))
    for i in range(len(X_test)):
        y_pred[i] = (m*X_test[i]).sum()
    return y_pred
y_pred = predict(m,X_test.values)
print(y_pred)
np.savetxt("y_pred_combined_cycle_power_plant.csv",y_pred)

[471.74297211 471.02526715 432.96734674 ... 440.18122705 453.14288186
 451.70532584]
